apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: prettier-knative-net-istio-
  namespace: default
spec:
  taskRef:
    name: prettier
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/knative/net-istio.git
    params:
    - name: ORGANIZATION
      value: knative
    - name: REPOSITORY
      value: net-istio
    - name: ASSIGNEE
      value: tcnghia
