apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: update-deps-google-knative-gcp-
  namespace: default
spec:
  taskRef:
    name: dep-update
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/google/knative-gcp.git
    params:
    - name: ORGANIZATION
      value: google
    - name: REPOSITORY
      value: knative-gcp
    - name: DEPENDENCIES
      value: knative.dev/test-infra knative.dev/pkg knative.dev/eventing knative.dev/serving
    - name: ASSIGNEE
      value: nachocano
