apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: update-deps-mattmoor-mink-
  namespace: default
spec:
  taskRef:
    name: dep-update
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/mattmoor/mink.git
    params:
    - name: ORGANIZATION
      value: mattmoor
    - name: REPOSITORY
      value: mink
    - name: DEPENDENCIES
      value: knative.dev/test-infra knative.dev/pkg knative.dev/serving  knative.dev/eventing github.com/mattmoor/http01-solver github.com/tektoncd/pipeline
    - name: ASSIGNEE
      value: mattmoor
